version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: tris-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tris_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: tris-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./tris-backend
      dockerfile: Dockerfile
      target: development
    container_name: tris-backend
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tris_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./tris-backend:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run start:dev

  frontend:
    build:
      context: ./tris-frontend
      dockerfile: Dockerfile
      target: development
    container_name: tris-frontend
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - VITE_SOCKET_URL=http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./tris-frontend:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data:
